(defun areaCuadrado (a b )
(princ "Dame un numero")
(read a)
(princ ("Dame otro numero"))
(*a b) 

)
(defvar *areaCuadrado* (lambda a b)(* a b))

defun dameDatos()
(princ "Dame dato")
(setq a (read))
(princ "Dame otro dato")
(setq b (read))
(format t "El resultado es ~A" (funcall *areaCuadrado* a b))